
package mw.facebook.imported;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MWFacebookService", targetNamespace = "http://facebook.mw/", wsdlLocation = "http://localhost:18081/MWFacebookService?wsdl")
public class MWFacebookService
    extends Service
{

    private final static URL MWFACEBOOKSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mw.facebook.imported.MWFacebookService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mw.facebook.imported.MWFacebookService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:18081/MWFacebookService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:18081/MWFacebookService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MWFACEBOOKSERVICE_WSDL_LOCATION = url;
    }

    public MWFacebookService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MWFacebookService() {
        super(MWFACEBOOKSERVICE_WSDL_LOCATION, new QName("http://facebook.mw/", "MWFacebookService"));
    }

    /**
     * 
     * @return
     *     returns MWMyFacebookService
     */
    @WebEndpoint(name = "MWMyFacebookServicePort")
    public MWMyFacebookService getMWMyFacebookServicePort() {
        return super.getPort(new QName("http://facebook.mw/", "MWMyFacebookServicePort"), MWMyFacebookService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MWMyFacebookService
     */
    @WebEndpoint(name = "MWMyFacebookServicePort")
    public MWMyFacebookService getMWMyFacebookServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://facebook.mw/", "MWMyFacebookServicePort"), MWMyFacebookService.class, features);
    }

}
