
package mw.facebook.imported;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "MWUnknownIDException", targetNamespace = "http://facebook.mw/")
public class MWUnknownIDException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MWUnknownIDException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public MWUnknownIDException_Exception(String message, MWUnknownIDException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public MWUnknownIDException_Exception(String message, MWUnknownIDException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mw.facebook.imported.MWUnknownIDException
     */
    public MWUnknownIDException getFaultInfo() {
        return faultInfo;
    }

}
