#==================================================================================================
#
#  Advanced Programming Techniques (AdvPT)
#  Winter Term 2009
#  Assignment 3 - Makefile
#
#==================================================================================================

BINARIES = main5 main8

CXX = g++
CXXFLAGS = -pedantic -ansi

all: $(BINARIES)

.PHONY: clean

clean:
	@$(RM) $(BINARIES)
