#==================================================================================================
#
#  Advanced Programming Techniques (AdvPT)
#  Winter Term 2009
#  Assignment 4 - Makefile
#
#==================================================================================================

BINARIES = main2 main3 main7 main8 main9

CXX = g++
CXXFLAGS = -pedantic -ansi

all: $(BINARIES)

.PHONY: clean

clean:
	@$(RM) $(BINARIES)
