# KLAUS: For C++ compilation you require to set the CXX and CXXFLAGS variables. In your case, both
#        variables are ignored since you only have cpp-files.
CC=gcc
CFLAGS=-Wall
main: main1 main2 main3 main9 main10 main11 main12


clean:
		rm -f main1 main2 main3 main9 main10 main11 main12

