#==================================================================================================
#
#  Advanced Programming Techniques (AdvPT)
#  Winter Term 2009
#  Assignment 3 - Makefile
#
#==================================================================================================

BINARIES = constness class_hierarchies smart_pointer test_exam_ex9 assignment1_2 assignment1_10 assignment1_11 assignment1_12 assignment2_5 explicitness swap_trick iterator_test

CXX = g++
CXXFLAGS = -pedantic -ansi -g

all: $(BINARIES)

.PHONY: clean

clean:
	@$(RM) $(BINARIES)
