#==================================================================================================
#
#  Advanced Programming Techniques (AdvPT)
#  Winter Term 2009
#  Assignment 3 - Makefile
#
#==================================================================================================

BINARIES = constness class_hierarchies smart_pointer test_exam_ex9

CXX = g++
CXXFLAGS = -pedantic -ansi -g

all: $(BINARIES)

.PHONY: clean

clean:
	@$(RM) $(BINARIES)
