
package mw.pathclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MWMyPathService", targetNamespace = "http://path.mw/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MWMyPathService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns mw.pathclient.StringArray
     * @throws MWNoPathException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public StringArray calculatePath(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws MWNoPathException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns mw.pathclient.StringArray
     * @throws MWNoPathException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public StringArray calculatePathSlow(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws MWNoPathException_Exception
    ;

}
