
package mw.pathclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@SuppressWarnings("serial")
@WebFault(name = "MWNoPathException", targetNamespace = "http://path.mw/")
public class MWNoPathException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MWNoPathException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public MWNoPathException_Exception(String message, MWNoPathException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public MWNoPathException_Exception(String message, MWNoPathException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mw.pathclient.MWNoPathException
     */
    public MWNoPathException getFaultInfo() {
        return faultInfo;
    }

}
