
package mw.pathclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MWPathService", targetNamespace = "http://path.mw/", wsdlLocation = "http://faucalyptus23.informatik.uni-erlangen.de:42042/MWPathService?wsdl")
public class MWPathService
    extends Service
{

    private final static URL MWPATHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mw.pathclient.MWPathService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mw.pathclient.MWPathService.class.getResource(".");
            url = new URL(baseUrl, "http://faucalyptus23.informatik.uni-erlangen.de:42042/MWPathService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://faucalyptus23.informatik.uni-erlangen.de:42042/MWPathService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MWPATHSERVICE_WSDL_LOCATION = url;
    }

    public MWPathService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MWPathService() {
        super(MWPATHSERVICE_WSDL_LOCATION, new QName("http://path.mw/", "MWPathService"));
    }

    /**
     * 
     * @return
     *     returns MWMyPathService
     */
    @WebEndpoint(name = "MWMyPathServicePort")
    public MWMyPathService getMWMyPathServicePort() {
        return super.getPort(new QName("http://path.mw/", "MWMyPathServicePort"), MWMyPathService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MWMyPathService
     */
    @WebEndpoint(name = "MWMyPathServicePort")
    public MWMyPathService getMWMyPathServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://path.mw/", "MWMyPathServicePort"), MWMyPathService.class, features);
    }

}
