# KLAUS: For C++ compilation you require to set the CXX and CXXFLAGS variables. In your case, both
#        variables are ignored since you only have cpp-files.
CC=gcc
CFLAGS=-Wall
main: main5 main6 main7 main8 main9 main12


clean:
		rm -f main5 main6 main7 main8 main9 main12

