#==================================================================================================
#
#  Advanced Programming Techniques (AdvPT)
#  Winter Term 2010
#  Assignment 5 - Makefile
#
#==================================================================================================

BINARIES = main4 main5 main8 main9

CXX = g++
CXXFLAGS = -pedantic -ansi

all: $(BINARIES)

.PHONY: clean

clean:
	@$(RM) $(BINARIES)
